### ISSUE TITLE
Toggle console output

### ISSUE THREAD

**Issue by danpacgig** [jandelgado/rabtap#11]
It would be nice if it were possible to not show any output to console windows.
If you are tapping a high frequency exchange, the console slows down the saving of the messages as json files by quite a bit.

**Comment by jandelgado** [comment]
Did you try to redirect output to /dev/null? Perhaps this already does the trick.

**Comment by danpacgig** [comment]
I didn't, but good idea, i tried it and its much faster. Thanks.
So its an option for sure, but would be nice as a feature.

**Comment by jandelgado** [comment]
Will be addressed by #32 (new option `--silent`)

**Comment by jandelgado** [comment]
Implemented in v1.21: use new `--silent` option
