### ISSUE TITLE
Allow ':' in exchange name

### ISSUE THREAD

**Issue by nizmow** [jandelgado/rabtap#13]
When tapping exchanges, ':' is used as a separator. Unfortunately, I'm using a framework (MassTransit) that creates exchanges with ':' in them (it uses type URNs for bindings), and it doesn't look like there's any way to escape it, since the code just uses a split.

Is it possible to provide some way to tap exchanges that include a ':'? Perhaps allow some kind of escaping? Ideally, a different character should be used for separating exchange and key, the AQMP spec (https://www.rabbitmq.com/amqp-0-9-1-reference.html) says:

>The exchange name consists of a non-empty sequence of these characters: letters, digits, hyphen, underscore, period, or colon.

So there are plenty of other options. Of course, this would break existing scripts which is far from ideal.

Thanks!

**Comment by jandelgado** [comment]
It's always a good idea to study the documentation before beginning with the implementation ;)
I'll allow to add escape-sequences in the exchange/binding configuration, e.g.
`exchange\\:with\\:colon:key` will be translated to exchange `exchange:with:colon` and `key`.

**Comment by nizmow** [comment]
I love it! Thank you.

**Comment by jandelgado** [comment]
Fixed in v1.18
