### ISSUE TITLE
Disable auto-ack in subscribe

### ISSUE THREAD

**Issue by HardlyMirage** [jandelgado/rabtap#15]
I have a usecase where I would like to disable auto-ack.
It would be nice to make those argument configurable.

https://github.com/jandelgado/rabtap/blob/76360a7ab4a4460a6073cbcd2440ac9654f09fe2/pkg/subscribe.go#L122

**Comment by jandelgado** [comment]
Yes, I also was thinking this feature could be useful. Will add it soon.

**Comment by jandelgado** [comment]
I added a new option `--no-auto-ack` to the `sub` command:

`rabtap sub QUEUE [--uri URI] [--saveto=DIR] [--no-auto-ack] [-jkvn]`

It's on the master, you can test it.

**Comment by jandelgado** [comment]
Will be available with next rabtap release.
