### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by radmen** [jandelgado/rabtap#24]
Hey,

FYI - I've created an AUR package for rabtap https://aur.archlinux.org/packages/rabtap-bin/
It can be installed on Arch-like systems using one of the AUR clients (eg. `yay`).

If you want to you can add this to the installation guides. If not, feel free to close this issue :)

**Comment by jandelgado** [comment]
Excellent - thanks. Since I did not use Arch for a while, would `sudo pacman -S rabtap-bin` / `sudo yay -S rabtap-bin` be the correct way to install?

**Comment by radmen** [comment]
Pacman does not handle AUR packages. IIRC it should be: `yay -S rabtap-bin`

czw., 22 sie 2019, 21:20 użytkownik jandelgado <notifications@github.com>
napisał:
