### ISSUE TITLE
Timestamp is never set

### ISSUE THREAD

**Issue by duynii** [jandelgado/rabtap#3]
Am I missing something or when I use tap mode the Timestamp is never set:

{
  "ContentType": "application/json",
  "ContentEncoding": "UTF-8",
  "DeliveryMode": 0,
  "Priority": 0,
  "CorrelationID": "",
  "ReplyTo": "",
  "Expiration": "1296000000",
  "MessageID": "",
  "Timestamp": "0001-01-01T00:00:00Z",
  "Type": "",
  "UserID": "",
  "AppID": "",
  "DeliveryTag": 6,
  "Redelivered": false,
  "Exchange": "some_exchange",
  "RoutingKey": "sdn.all"
}

**Comment by jandelgado** [comment]
As far as I know, the "Timestamp" header is application defined, the publisher has to set it. It will not automatically set by the broker. Are you sure it is set by you application?

**Comment by jandelgado** [comment]
Closed as not being a bug.
