### ISSUE TITLE
Is it possible to tap queue on default exchange?

### ISSUE THREAD

**Issue by andrewmweaver89** [jandelgado/rabtap#33]
When attempting to run `rabtap tap -v  "":<my queue name>`. I receive 

```
INFO[0000] waiting for new session ...
INFO[0000] got new session ...
INFO[0000] tap: bind to exchange  failed with Exception (403) Reason: "ACCESS_REFUSED - operation not permitted on the default exchange"
INFO[0000] delete exchange: <nil>
DEBUG[0000] subscribe: cancel
INFO[0000] session: shutting down factory (cancel)
ERROR[0000] tap failed with Exception (403) Reason: "ACCESS_REFUSED - operation not permitted on the default exchange
```
I believe the issue may be we are trying to bind the queue to the default exchange. Am I completely misunderstanding? I am new to rabbit so any help would be appreciated.

Also let me know if I can assist in anyway.

**Comment by jandelgado** [comment]
Hi, when tapping messages, `rabtap` is creating a temporary exchange-to-exchange binding on the exchange being tapped. It seems that RabbitMQ does not generally allow to bind to the default exchange, as this code excerpt from RabbitMQ suggests (if I intepret it correcty):

https://github.com/rabbitmq/rabbitmq-server/blob/79da341df49a8fc54229b930bd0e8d52f4209f64/src/rabbit_channel.erl#L1950-L1960

To solve your problem, you could bind your queue e.g. to the `amq.direct` exchange and then `tap` this exchange with the queues name as the binding key.

**Comment by andrewmweaver89** [comment]
Ok. so currently all my queues are just using the default exchange(""). If I understand you correctly, I would need to bind my queue to `amq.direct` and then have all my messages directed to that exchange?

**Comment by jandelgado** [comment]
Yes, there are many options depending on your requirements. RabbitMQ supports different exchange types (e.g. direct, fanout, topic, header), which define how messages are routed. When using the pre-defined `amq.direct` exchange (type `direct`), you bind your queue to this exchange using a provided binding key, e.g. `MYKEY`. Published messages to exchange `amq.direct` are routed to all queues where the provided routing key equals the binding key (e.g. `MYKEY`).

Have a look at the [basic concepts documentation](https://www.rabbitmq.com/tutorials/amqp-concepts.html) of RabbitMQ [and the official tutorials](https://www.rabbitmq.com/getstarted.html) for further information.

**Comment by andrewmweaver89** [comment]
Awesome. Thanks for the prompt, detailed reply!

**Comment by AnthonyMastrean** [comment]
@andrewmweaver89 we encountered the same problem, here's what you can do _without_ changing your queue bindings...

1. Turn on the [firehose tracer](https://www.rabbitmq.com/firehose.html)
```
rabbitmqctl trace_on
```

1. Tap the trace exchange
```
raptap amq.rabbitmq.trace:#
```

**Comment by jandelgado** [comment]
Thanks for the info, I'll put it in the FAQ.

**Comment by jmgarnier** [comment]
Thanks @AnthonyMastrean I think you saved me a lot of time. Putting it in the FAQ will help a lot of people. I can push a PR. But where is the FAQ? Maybe the 1st https://github.com/jandelgado/rabtap#examples ?

**Comment by jandelgado** [comment]
Hi, I documented the example in #44 , will merge after a review. BR jan
