### ISSUE TITLE
Feature request: Allow replay from `--saveto` directory

### ISSUE THREAD

**Issue by jerry73204** [jandelgado/rabtap#34]
I'm working on a project that exchanges ProtoBuf serialized messages. By default rabtap dumps the binary to stdout and messes up my terminal. I see redirection `rabtap ... > /dev/null` is a workaround for this. I would be glad if the stdout can be turned off and keeps `--saveto` option.

EDIT:
Change the title for more clarification.

**Comment by jerry73204** [comment]
Sorry I missunderstand the usage. It seems the _batch replay_ is only possible if I add `--json` option. So let me elaborate the thoughts.

In my minor opinion, I would prefer to replay the messages produced by `--saveto` rather than single JSON file. Here are my arguments,

- My rabbitmq serves high throughput (1GB in 10s). It's cumbersome to inspect a single large JSON file (produced by `--json`). Also the ASCII storage is inefficient.
- The `--saveto` option gives me the freedom to inspect the raw messages in separate files. That is, I don't need to open a large JSON file, copy the message, and transform to binary back. I wonder if it's possible to replay the messages from directory, or even I can choose subset of messages.

**Comment by jandelgado** [comment]
Hi, sound like a good idea. Will add it to the backlog.

**Comment by jandelgado** [comment]
Will be tracked in #10
