### ISSUE TITLE
UUID Api update: Multiple-value uuid.NewV4() in single-value context 

### ISSUE THREAD

**Issue by krisshhh** [jandelgado/rabtap#4]
Unable build pkg because of uuid api update, uuid.NewV4() now returns two values, uuid and error. can you please update the code accordingly.

**Comment by jandelgado** [comment]
What exactly are you trying to do - how can I reproduce the probelm?
Which version of go are you using?

**Comment by jandelgado** [comment]
any update from your side?

**Comment by jandelgado** [comment]
closed because not reproducible and inactivity

**Comment by stevenklassen8376** [comment]
Would you consider re-opening this? The problem is that the latest version of the UUID package has a breaking API change as shown below.

    // NewV4 returns random generated UUID.
    func NewV4() (UUID, error) {
    	    return global.NewV4()
    }

If you are willing to re-open this, I would be happy to implement the fix.

**Comment by stevenklassen8376** [comment]
Never mind, I see it now. To build with GOLAND you have to manually switch the uuid package to the 1.2.0 tag.

**Comment by jandelgado** [comment]
I changed the UUID lib used to https://godoc.org/github.com/google/uuid and expect the problem to disappear. Will be released with next release (1.17)
