### ISSUE TITLE
Enhancement: To allow run 'rabtap tap' as a background process (with a switch parameter). So that other commands in the same script can continue without going in the taps 'listening' mode. 

### ISSUE THREAD

**Issue by PramodKumarYadav** [jandelgado/rabtap#41]
Often in our system tests, there are multiple steps involved including publishing, tapping multiple exchanges, sorting, comparing etc all. 

To be able to do all these steps in say a PowerShell script, without going in the 'tap mode', I have to tap the exchanges using background jobs (start-job). Later I do a (receive-job) to get the data from these jobs to say an output file. 

Is it possible to give background-processing as an option in the tap command? So that when this flag is selected, we can continue with the next steps in the current script without having to create these jobs (for tap commands). This would add more readability to the code and is a day to day use case in a system test scenario with more commands in same script (doing publish, multiple exchange taps and other operations for say sort/compare etc). 

P.S: I know there are workaround like (start-job and start-process) to achieve this but having this as a part of the command parameter, would be awesome! 

Dont know if that is possible though?

**Comment by jandelgado** [comment]
I would prefer to not put this into rabtap as it is not meant to run as a daemon. On linux/unix systems you simply could add a `&` at the end of the rabtap invocation in the shell to make it run in the background, e.g. `$ rabtap tap --saveto /tmp/test &`. When running as a background process, you also need to think about how the process can now be terminated (e.g. send TERM signal).

**Comment by PramodKumarYadav** [comment]
Point taken. This was the exact same remark and solution I got from my buddy. I am closing this.
