### ISSUE TITLE
Any interest in extending rabtap to be able to use S3?

### ISSUE THREAD

**Issue by leopoldodonnell** [jandelgado/rabtap#50]
This is an awesome tool. Many thanks @jandelgado !

I've been roped into performance testing a new product which will require a ton of data in order to address all of our test scenarios. S3 would be the best solution for me for storage and playback.

I would be happy to fork and generate a PR that performs the same as the directory option works today for S3. 

Go is not a core capability at my company and I can't saddle our teams with a codebase outside of their skillset, so I would only do this if there was interest in accepting the PR (assuming good quality etc). Otherwise, I'll put `rabtap` in a pipeline controlled by a node or python app.

**Comment by jandelgado** [comment]
Hi, I think such an enhancement is to specific and not considered in the scope of rabtap. But perhaps it's possible to achieve the desired behaviour by using additional tools like e.g. tools `rclone` and perhaps `socat`. The idea would be to e.g. mount the bucket or use the `rclone` embedded web server and feed the data into rabtap.

**Comment by leopoldodonnell** [comment]
No problem - upon further thought, the number of Objects that my tests would need would not perform well with the one file per message approach, so I'm writing a wrapper.

Thx
