### ISSUE TITLE
Feature Request: Limit number of messages consumed

### ISSUE THREAD

**Issue by hrobertson** [jandelgado/rabtap#53]
Thanks for this really useful tool!
I'd like to be able to consume n messages per invocation.
Additionally I'd like to be able to use the --delay option when consuming to limit the rate at which messages are consumed.

eg `rabtap sub somequeue --limit 10 --delay 30s` would consume 1 message every 30s until 10 messages had been consumed.

Is this something you might consider implementing?
Thanks!

**Comment by jandelgado** [comment]
That just reminded me that already started building this feature in March, but somehow I had to change priorities and work stalled :-(

Thanks for the reminder. I just opened a PR for this (#54) 

I'll check if the `--delay` option can be easily added too.

**Comment by Antiarchitect** [comment]
Also need exact this feature!

**Comment by jandelgado** [comment]
@Antiarchitect, @hrobertson: I've added a `--limit=NUM` option and the ability to optionally  reject/requeue messages. You can build a version to test with `go get github.com/jandelgado/rabtap/cmd/rabtap@489cddc`. Please tell me if this works for you

**Comment by Antiarchitect** [comment]
@jandelgado Worked like a charm for me! Thank you once again!

**Comment by hrobertson** [comment]
Thanks @jandelgado This looks good.
I'm not working with Rabbit these days but I'm sure I'll make use of this feature in the future.

Thanks!
