### ISSUE TITLE
Feature Request: Terminate after all messages are consumed from queue

### ISSUE THREAD

**Issue by manuel-koch** [jandelgado/rabtap#56]
I like to use rabtap to consume all messages from a DeadLetter/ParkinLot queue to inspect them and later maybe re-publish them.

Currently rabtap seem to continue to consume message from given queue without ever terminating ( unless I hit Ctrl-C ).

Would be nice if rabtap would terminate ( after a given timeout ) when no more messages where consumed from given queue.

**Comment by jandelgado** [comment]
Could you provide an example on how you invoke rabtap so I can reproduce the behaviour?

**Comment by Antiarchitect** [comment]
@jandelgado I need some kind of this feature too. I will use your tool for e2e testing of my project so it would be very nice  to have a flag some kind of `rabtap sub <queue> --consume n` - in order to consume exact `n` messages, then disconnect and `exit 0`

**Comment by Antiarchitect** [comment]
OMG you already have it! https://github.com/jandelgado/rabtap/pull/54 Please :))

**Comment by jandelgado** [comment]
The PR is not yet finished, will work on it the next days

**Comment by Antiarchitect** [comment]
Thank you so much @jandelgado <3

**Comment by jandelgado** [comment]
@manuel-koch: release 1.35 adds  a new `--idle-timeout=DURATION` option to the sub and tap commands, which allows to terminate after a given period of inactivity
