### ISSUE TITLE
go 1.16+ is required to build from sources

### ISSUE THREAD

**Issue by trufanov-nok** [jandelgado/rabtap#80]
I tried to build rabtap in Astra Linux which has golang 1.15.0 in repos and failed with error:

```
github.com/rabbitmq/amqp091-go
/home/username/go/pkg/mod/github.com/rabbitmq/amqp091-go@v1.5.0/connection.go:919:16: undefined: os.ReadFile
note: module requires Go 1.16
```

So I'm suggesting to update ReadMe.md as go 1.12 requirement is listed there.

**Comment by jandelgado** [comment]
According to go.mod, it's 1.18:

https://github.com/jandelgado/rabtap/blob/a9bca81bc6c8b6646fe9c01317f0be32682a84e1/go.mod#L3

I'll update the documentation
